l=[
    "Describe the types of Data Structures?",
    "What is a Stack?",
    "What are the operations that can be performed on a stack?",
    "What is the difference between NULL and VOID?",
    "Can you declare an interface method static? explain your answer?",
    "Can the Interface be final? explain your answer?",
    "How many types of database languages are?",
    "What are the types of entity Relationship?",
    "Who is the founder of C language?",
    "what is list in python?",
    "what is NLP"
]
TechM=[
        "What do you understand by Function Overloading?",
        "Name a few Object Oriented Programming languages?",
        "What are Destructors in C++?",
        "What do you understand by a checkpoint in Database Management Systems?",
        "What are transparent Distributed Database Management Systems?",
        "State the pros of multithreaded programming?",
        "What do you know about C++ or C tokens?",
        "What do you know about our company?",
        "Why should we hire you at Tech Mahindra?",
        "How can you contribute to the growth of our company?"
      ]
IBM=[
      "Explain the major concepts of Object Oriented Programming in the context of C++ programming language?",
      "Explain function overloading and function overriding in the context of C++ programming language?",
      "What are the functions of an operating system?",
      "Differentiate between primary memory and secondary memory in the context of a computer",
      "What is a DataBase Management System?",
      "Differentiate between struct and union in the context of C programming language?",
      "What do you understand about a deadlock in the context of operating systems?",
      "Differentiate between quick sort and merge sort in the context of sorting algorithms",
      "What do you understand about an entry controlled loop in the context of OOPs programming?",
      "What are the three types of schedulers in the context of operating systems?",
      "What do you know about virtual memory in the context of operating systems?",
      "What is the purpose of the sudo command in the context of the UNIX operating system?",
      "What do you understand about arrays?",
      "Differentiate between variable/ function declaration and definition in the context of any OOPs programming language.",
      "What do you understand about processes and threads in the context of an operating system?"
]
HCL=[
      "What is the use of the finalize() method in Java?",
      "What is the use of polymorphism in Java?",
      "What is input-output (I/O) in C++?",
      "What is the difference between a constant variable and a global variable?",
      "What do you mean by nested classes?",
      "What is the meaning of the term Big Data?",
      "Name some software analysis & design tools?",
      "What is the major difference between structured English and Pseudo Code?",
      "What is the use of the pointer in C?",
      "How do you achieve multiple inheritances in Java?",
      "What is init in Python?",
      "What is the role of Domain Name System (DNS)?",
      "What are constraints in SQL?",
      "What are aggregate functions in SQL?",
      "What are some of the differences between C & C++?"
]
Infosys=[
      "What is an Object in OOPs?",
      "What is a Class in OOPs?",
      "What is a constructor?",
      "Explain OOPs in Brief?",
      "Mention some limitations of OOPs.",
      "What distinguishes SQL and MySQL from one other?",
      "What is the difference between TCP and UDP?",
      "What is SDLC (Software Development Life Cycle)?",
      "Explain a network and node?",
      "How is polymorphism implemented in Java?",
      "What are clustered indexes?",
      "What are SQL triggers?",
      "What is a database schema?",
      "What are the disadvantages of the waterfall model?",
      "What is the difference between a session and a socket?"
]
Wipro=[
      "What are the functionalities of an operating system?",
      "What is the difference between UNIQUE key and PRIMARY key constraints?",
      "Define the SQL Profiler?",
      "What is stored procedure?",
      "What is a process and what is a thread?",
      "What are the advantages of a thread? How does the multithreading look like?",
      "What are Multi-Processing and Multitasking?",
      "What are the differences between an object-oriented programming language and object-based programming language?",
      "What are the differences between error and exception in Java?",
      "Differentiate between strings and char arrays in Java.",
      "Explain precondition and postcondition to a member function in the context of C++ programming language?",
      "What is polymorphism?",
      "What is DOM?",
      "Name the operators that cannot be overloaded.",
      "What are some of the differences between C & C++?"
]
Amazon=[
      "Why do you want to join Amazon?",
      "Why should we hire you?",
      "What does success mean to you?",
      "What are checked exceptions?",
      "What is hashing?",
      "What is a search operation?",
      "What is the purpose of the 'is' operator in Python?",
      "What is data structure?",
      "What is Collections API?",
      "What is the Tower of Hanoi?",
]
Apple=[
      "Why should we hire you?",
      "If you accepted a job with Apple, what would you miss most about your current position?",
      "Why do you want to join Apple?",
      "Describe a time that you went above and beyond for a customer.",
      "How would you handle a co-worker who was distracting you?",
      "What would you do if a customer came in with an iPhone that was not working?",
      "Name three accessibility features that are available on the iPhone.",
      "What are the different ways of achieving concurrency in iOS?",
      "Which JSON framework does iOS support? What are its advantages?",
      "What are the different joins in SQL?",
]
Capgemini=[
      "Why should one utilise a Database Management System (DBMS)? Explain its advantages?",
      "Why is normalisation needed in a database?",
      "What is the difference between UNION and UNION ALL?",
      "Differentiate between Dataset.clone() and Dataset.copy()?",
      "Differentiate between getch() and getche()?",
      "What do you know about #pragma directive?",
      "What is the drawback of scanf() and how can it be avoided (if any)?",
      "How is memory managed in Python?",
      "What are the advantages of NumPy arrays over Python lists?",
      "What is Java String Pool?",
]
Cognizant=[
      "What are character constants in C++?",
      "Define the terms OSI, TCP, and IP?",
      "Give me a Query to find out the largest compensation in an organization?",
      "What are derived data types? Name the user defined data types in C++?",
      "Explain tokens in C++.Also tell about their role and importance?",
      "Can a database table exist without a primary key?",
      "What is the reason behind using Inner Join and Outer Join ?",
      "What is the top-n analysis in DBMS?",
      "What is object oriented model?",
      "Define RDBMS.",
]
Deloitte=[
      "What is backpropagation?",
      "What is the difference between a crossover and a straight-through?",
      "What is SMTP?",
      "What made you want to find a new job?",
      "Why should we hire you Deloitte?",
      "What is a volatile keyword?",
      "What are the differences between stored procedure and triggers in SQL?",
      "What do you understand about tunneling protocol in Computer Networks?",
      "Discuss the physical layer of the OSI Model in context of Computer Networks?",
      "How can you contribute to the growth of our company?",
]
Google=[
      "What is your knowledge of Google's history",
      "In your opinion, should people have to use their legal names when setting up a Gmail account?",
      "What do you think of Google charging for their productivity apps? Do you agree or disagree?",
      "What does multithreaded programming mean?  ",
      "If you were told to create an initiative to increase Gmail's user base, what would you do?",
      "How do cookies move along through the HTTP protocol?",
      "What steps could YouTube take to improve its business model?",
      "Could you explain why the Google homepage is mostly blank?",
      "What is Google's largest concern right now?",
      "Given an autosuggest issue in a developing country, what steps would you take to correct it? ",
]
Microsoft=[
      "Define objects and classes in C++?",
      "In C++, how do you allocate and release memory?",
      "What are Microsoft security patches?",
      "What is the difference between standard modules and class modules?",
      "Why is it that you cannot overload the scope resolution operator (::)?",
      "What is plug and play?",
      "Why is code optimization important?",
      "Why are there different Microsoft Certifications?",
      "Which Microsoft Certification is considered the most popular?",
      "Why do you want to work for Microsoft?",
]
Amazon=[
      "What is backpropagation?",
      "Why should we hire you?",
      "What does success mean to you?",
      "What are checked exceptions?",
      "What is hashing?",
      "What is a search operation?",
      "What is the purpose of the 'is' operator in Python?",
      "What is data structure?",
      "What is Collections API?",
      "What is the Tower of Hanoi?",
]
AWS=[
    "What are the 3 types of cloud services AWS has?",
    "What is the relation between the Availability Zone and Region?",
    "What is auto-scaling?",
    "what is cloudwatch?",
    "What is an Elastic Transcoder?",
    "What is AWS?",
    "What are the main components of AWS?",
    "What is the importance of buffer in AWS?",
    "What are key-pairs?",
    "What is an AMI?",
]
AI=[
    "What is Artificial Intelligence?",
    "List out the various applications of AI?",
    "How many Types of Artificial Intelligence are there? What are they?",
    "What are the stages of learning AI?",
    "What is an intelligent agent in Artificial Intelligence?",
    "What is the difference between Strong AI and Weak AI?",
    "What are the commonly used types of neural networks in AI?",
    "What is an Artificial Neural Network?",
    "What is the Turing test?",
    "What is FOPL in Artificial Intelligence?",
]
Front_End=[
    "What npm stands for?",
    "What is scope in JavaScript?", 
    "What is User Centered Design?",
    "What is Coercion in JavaScript?", 
    "What is IIFEs?",
    "State the elements of the CSS Box Model?",
    "How are JavaScript and jQuery different?",
    "What is Content Security Policy?",
    "What is Cross-Site Scripting (XSS)?",
    "State some basic design element?",
]
Devops=[
      "What is DevOps?",
      "What are the key components of DevOps?",
      "What is the role of version control in DevOps?",
      "What is continuous integration (CI) in DevOps?",
      "What is continuous delivery (CD) in DevOps?",
      "What is infrastructure as code (IaC) in DevOps?",
      "What is the role of containers in DevOps?",
      "What is continuous monitoring in DevOps?",
      "What is the difference between continuous deployment and continuous delivery?",
      "What are some key benefits of implementing DevOps practices?",
]
Cyber_Security=[
      "What is cybersecurity?",
      "What are the main goals of cybersecurity?",
      "What is the CIA triad in cybersecurity?",
      "What is a firewall?",
      "What is encryption?",
      "What is a vulnerability assessment?",
      "What is a phishing attack?",
      "What is a DDoS attack?",
      "What is endpoint security?",
      "What is the difference between penetration testing and vulnerability scanning?",
]
ML=[
      "What is machine learning?",
      "What are the main types of machine learning?",
      "Can you explain the difference between supervised and unsupervised learning?",
      "What is overfitting in machine learning?",
      "How do you prevent overfitting in a machine learning model?",
      "What is the bias-variance tradeoff in machine learning?",
      "What is the difference between batch gradient descent and stochastic gradient descent?",
      "What is a confusion matrix?",
      "What is precision and recall?",
      "What is cross-validation?",
]