ans={
    "Describe the types of Data Structures?":"Data Structures are mainly classified into two types, Linear Data Structure and Non-Linear Data Structures",
    "What is a Stack?":"Stack is an ordered list in which, insertion and deletion can be performed only at one end that is called the top.",
    "What are the operations that can be performed on a stack?":"Push Operations,Pop Operations,Peek Operations, also called as insertion,deletion and top",
    "What is the difference between NULL and VOID?":"Null is actually a value, whereas Void is a data type identifier.",
    "Can you declare an interface method static? explain your answer?":"No, because methods of an interface are abstract by default, and we can not use static and abstract together.",
    "Can the Interface be final? explain your answer?":"No, because an interface needs to be implemented by the other class and if it is final, it can't be implemented by any class.",
    "How many types of database languages are?":"There are four types of database languages Data Definition Language (DDL).Data Manipulation Language (DML) Data Control Language (DCL) Transaction Control Language (TCL)",
    "What are the types of entity Relationship?":"There are three type of relationships in DBMS. One-To-One, One-To-Many or many-to-one,  Many-to-many",
    "Who is the founder of C language?":"Dennis Ritchie",
    "what is list in python?":"List is a linear data type,which is ordered,changable and indexed",
    "what is NLP":"NLP stands for Natural Language Processing"
    }
TechM={
        "What do you understand by Function Overloading?":"Object-Oriented programming has a feature called function overloading, which allows two or more functions to have the same name but distinct parameters name should be the same in Function Overloading, but the arguments should be different",
        "Name a few Object Oriented Programming languages?":"C++,Java,Python,PHP,JavaScript",
        "What are Destructors in C++?":"Destructors in C++ are instance member functions that are automatically called whenever an object is destroyed.Destructors are usually used to deallocate memory and cleanups for a class object and its class members when the object is destroyed",
        "What do you understand by a checkpoint in Database Management Systems?":"The Checkpoint in DBMS is a technique that removes all previous logs from the system and stores them permanently on the storage drive.",
        "What are transparent Distributed Database Management Systems?":"The transparent Distributed Database Management System conceals its physical structure from users.Transaction transparency,Performance transparency,DBMS transparency, Distribution transparency.",
        "State the pros of multithreaded programming?":"There is resource sharing in multithreaded programming,improves the responsiveness of the system,parallel processing,multiprocessing architecture.",
        "What do you know about C++ or C tokens?":"token is basically the program's smallest components,Tokens are following types:Keywords,Strings,Identifiers,Special Symbols,Constants,Operators.",
        "What do you know about our company?":"I know that Anand Mahindra established it in 1986 as part of the Mahindra group. The company has been providing IT and consulting services to its clients. Though its headquarters are in Pune, it has offices across the country.",
        "Why should we hire you at Tech Mahindra?":"I believe that my knowledge and experience can be an asset to the organisation's growth,where I have been responsible for acquiring customers, maintaining relationships with them and retaining them.",
        "How can you contribute to the growth of our company?":"I can contribute to the growth of the company using my skills, qualifications and acquired experience. Several of my values, such as professionalism, quality and focus, match those of the organisation."
}
IBM={
      "Explain function overloading and function overriding in the context of C++ programming language?":"Function Overloading It allows for multiple definitions of the function by modifying the signature, i.e. the number of parameters, the datatype of the parameters, and the return type.Function Overriding:It is the redefining of a base class function in a derived class with the same signature, that is, the return type and parameters. It's only possible in derived classes.",
      "What are the functions of an operating system?":"The functions of an operating system Provides user interface,Maintains system performance,Error-detection,Memory Management,security.",
      "Differentiate between primary memory and secondary memory in the context of a computer":"Primary/Main Memory: The computer memory that is directly accessible by the CPU is referred to as primary memory.Example - RAM (Random Access Memory).Secondary Memory: Because the processor does not directly interface with the secondary memory, the contents of the secondary memory are first transferred to the primary memory and then accessed by the processor. Example - Hard disk, USB drive.",
      "What is a DataBase Management System?":"A database management system is a piece of software that manages databases.A database management system (DBMS) provides an interface for doing tasks such as building a database, saving data in it, updating data, and creating a table in the database, among others. ",
      "Differentiate between struct and union in the context of C programming language?":"struct: In C, a structure is a user-defined data type that allows you to combine data objects of various types. A record is represented by a structure.Union: In C, a union is a unique data type that allows you to store many data types in the same memory region. A union can have numerous members, but only one of them can have a value at any given time. Unions are a useful approach to reuse the same memory space for numerous purposes.",
      "What do you understand about a deadlock in the context of operating systems?":"A deadlock occurs when a group of processes is halted because each process is holding a resource and waiting for another process to obtain it.",
      "Differentiate between quick sort and merge sort in the context of sorting algorithms":"Quick Sort: In a quick sort, the array is divided into any ratio. In a quick sort, there is no requirement to divide the array of components into equal sectionsMerge Sort:The array is divided into only two halves (i.e. n/2) in the merge sort.",
      "What do you understand about an entry controlled loop in the context of OOPs programming?":"An entry control loop examines the condition at the point of entry and passes control to the body of the loop if the condition or expression becomes true.",
      "What are the three types of schedulers in the context of operating systems?":"The three types of schedules are:long terms,short terms,medium terms.",
      "What do you know about virtual memory in the context of operating systems?":"Virtual Memory is a storage allocation system that allows secondary memory to be addressed as if it were the main memory. The addresses used by an application to refer to memory are distinct from the addresses used by the memory system to designate physical storage sites, and program-generated addresses are automatically translated to machine addresses.",
      "What is the purpose of the sudo command in the context of the UNIX operating system?":"sudo is a short form of Super Users DO. In Linux, the sudo command is commonly used as a prefix to a command that only superusers are permitted to run. If you use the prefix 'sudo' before any command, it will run it with elevated privileges, allowing a user with the necessary permissions to run a command as another user, such as the superuser. This is the Windows version of the 'run as administrator' option. ",
      "What do you understand about arrays?":"A collection of items stored in contiguous memory spaces is referred to as an array. The objective is to group together goods of the same type. This makes calculating the position of each element easy by simply adding an offset to a base value, such as the memory address of the array's first element.",
      "Differentiate between variable/ function declaration and definition in the context of any OOPs programming language.":" Definition:Only one time can a variable or function be defined.Declaration:There is no limit to how many times a variable or function can be declared.",
      "What do you understand about processes and threads in the context of an operating system?":"Process: Any program in execution is referred to as a process. Any process is controlled by a process control block.Thread: A thread is a section of a process, which means that a process can have several threads, all of which are contained within the process."
}
HCL={
      "What is the use of the finalize() method in Java?":"The finalize () method in java is a special method similar to the main method in java. Before the garbage collector reclaims the object, finalize () method is called as its last chance for any object to perform a clean up activity.",
      "What is the use of polymorphism in Java?":" A reason why polymorphism is needed in Java is that the concept is extensively used in implementing inheritance. It plays a crucial role in allowing the object having a different internal structure to share the same external interface.",
      "What is input-output (I/O) in C++?":"In C++, the input stream is used to get inputs from the console i.e. the user. The output stream is used to display the results of the operations to the console, or to the output device. iostream represents the standard input-output stream in C++. It contains different methods like cin, cout etc.",
      "What is the difference between a constant variable and a global variable?":"Constant variables:Constant variables have a fixed value that cannot be modified throughout the program.Global variables:Global variables can be changed and are accessible by all the functions in a program.",
      "What do you mean by nested classes?":"Nested classes mean that we can define a class inside another class in an Object-oriented programming language (OOP). The enclosed class is called a nested class. A nested class has the same access rights as other members of the class and is like another member of the outer class.",
      "What is the meaning of the term Big Data?":"Big data, as the name suggests, means large volumes of data. The data available to us from multiple online platforms today is complex and huge. For traditional systems to analyze and process, and to interpret something meaningful from the data is quite challenging.",
      "Name some software analysis & design tools?":"Some of the most important software analysis and designing tools are:Data Flow Diagrams,Structured Charts,Structured English,Data Dictionary.",
      "What is the major difference between structured English and Pseudo Code?":"Structured English is used to write the structure of a program module. It is a native English language. It uses the keywords of programming language.Pseudo Code is more like a programming language without the syntax of any specific language.",
      "What is the use of the pointer in C?":"some of the important uses of pointers in C:To access array elements,For dynamic memory allocation,Call by Reference.",
      "How do you achieve multiple inheritances in Java?":"The only way to implement multiple inheritances is to implement multiple interfaces in a class. In Java, one class can implement two or more interfaces. As all methods declared in interfaces are implemented in the class, this does not cause any ambiguity.",
      "What is init in Python?":"‘init’ basically stands for initialization. The role of init is to create processes from the script stored in the file which is a configuration file. This is then to be used by the initialization system. The __init__ method is similar to constructors in C++ and Java.",
      "What is the role of Domain Name System (DNS)?":"The main role of the Domain Name System (DNS) is to translate domain names into IP Addresses. These IP addresses are the ones that computers can understand. It also gives a list of mail servers that accept Emails for each domain name.",
      "What are constraints in SQL?":"Constraints in SQL are the limits or rules that we can apply to the different types of data in a given table. Constraints are used to ensure the accuracy and reliability of the data in the table.",
      "What are aggregate functions in SQL?":"A function is a unit of code that is used for the purpose of reusability of a part of a program. An SQL aggregate function calculates on a set of values and returns a single value. The function should return a value.",
      "What are some of the differences between C & C++?":"A function is a unit of code that is used for the purpose of reusability of a part of a program. An SQL aggregate function calculates on a set of values and returns a single value. The function should return a value."
}
Infosys={
      "What is an Object in OOPs?":" An object is an instance or subset of the class. It is attributable to a physical operation such as individual attributes, properties and behavior. It occupies space in the memory and has member functions defined in a class.",
      "What is a Class in OOPs?":"A class gives the object's outline and has a fixed data type defined by the user. Member functions, variables, constants and other functionality are designated within a class. It does not use any memory during run time.",
      "What is a constructor?":"Constructors are used to initialize the data members of a new object. It prepares the object for run-time operation using keywords and member variables.",
      "Explain OOPs in Brief?":"Object-oriented programming allows programmers to express real-world situations using objects. An object is any entity that has states and behaviors. Shapes reflect an entity's qualities or data, whereas procedures describe an item's behaviors. Learners, employees, books, and other things are objects, and these objects communicate with each other by sending messages. A class serves as a blueprint for creating objects.",
      "Mention some limitations of OOPs.":"The following are some typical OOPs limitations: More prominent than other programmes in terms of size. It was labor-intensive to create, and it ran slower than other programmes. For some problems, it is improper.",
      "What distinguishes SQL and MySQL from one other?":"SQL: Structured Query Language, also known as  SQL, is a common  English language based language.MySQL: A database management system is MySQL.",
      "What is the difference between TCP and UDP?":"UDP is a protocol without connection. TCP is connection-oriented. UDP is much simpler, faster and more efficient than TCP.",
      "What is SDLC (Software Development Life Cycle)?":"An SDLC presents the life cycle of software in the diagrammatic form. It displays the software's methods for its complete development, maintenance, requirement analysis, etc.",
      "Explain a network and node?":"A network is a collection of gadgets linked together via a physical transmission.Node is another word for a device that is connected to a network. If two PCs, two machines, and a web server are all linked to a network, we may say there are five nodes within the network.",
      "How is polymorphism implemented in Java?":"Polymorphism can be implemented either through overloading at compile-time or overriding at run-time.",
      "What are clustered indexes?":"A clustered index is used to define the order in which the data will be tangibly stored in the table. If you add a primary key to a table, it automatically becomes a clustered index.",
      "What are SQL triggers?":"An SQL trigger is an object that raises an alarm when something happens in a database. For example, a trigger can be set to record the deletion of an entry from the database.",
      "What is a database schema?":"The database schema represents the overall logical framework of a database. It is an abstract structure made in one of the formal languages accepted by the database.",
      "What are the disadvantages of the waterfall model?":"The waterfall model is not user-friendly as it does not consider the end-product from the user-end.It is not flexible in terms of accommodating changes.",
      "What is the difference between a session and a socket?":"A session is a logical connection established between the source and the destination.A socket is the physical apparatus (an IP address and Port Number) used to implement a session."
}
Wipro={
      "What are the functionalities of an operating system?":" A user interface (UI), such as a graphical user interface (GUI) or a commandline (CL), is provided by an operating system (OS).",
      "What is the difference between UNIQUE key and PRIMARY key constraints?":"Unique key:Multiple unique keys can be found in a table.Primary key:There can only be one main key in a table.",
      "Define the SQL Profiler?":"SQL Profiler is a profiler utility primarily used to track SQL Server connections and determine actions such as which SQL Scripts are running andare failing, among other things.",
      "What is stored procedure?":"A stored procedure is a collection of SQL statements that can be run invarious ways. Most database management systems support stored procedures, butnot all of them.",
      "What is a process and what is a thread?":"THREAD: A thread is the slightest and minuscule processing unit, a lightweightsub-process, and a discrete execution path.Threads are self-contained, which implies that if one thread fails, it has noimpact on the others. It takes advantage of shared memory space.",
      "What are the advantages of a thread? How does the multithreading look like?":"It allows for effective communication.It reduces the amount of time it takes to switch between contexts.We can get concurrency within a process by using thread.",
      "What are Multi-Processing and Multitasking?":"Multitasking: Multiple jobs run on a single CPU, as the name implies. To get the most of the CPU, we use multitasking.Multi-processing: It describes a system’s ability to sustain several central processing units at the same time.",
      "What are the differences between an object-oriented programming language and object-based programming language?":"The main distinctions between object-oriented and object-based languages areas follows:Object-oriented languages have no built-in objects, but object-based languages have them. JavaScript, for example, has a built-in window object.",
      "What are the differences between error and exception in Java?":"Errors:It is impossible to recover from a compilation or execution fault.All mistakes in Java are of the unchecked kind.Exceptions:A try-catch block or the throw keyword can be used to recover fromexceptions.The program itself throws exceptions.",
      "Differentiate between strings and char arrays in Java.":" Strings:A string is a collection of characters represented as a single datatype in sequential order.Character Arrays:A Character Array is a sequenced array of char data types.",
      "Explain precondition and postcondition to a member function in the context of C++ programming language?":"Precondition – a condition that must be true before a function (or code segment) executes, in order. for the code to work correctly. Postcondition - a condition that will be true after a functions returns orat the end of a code segment.",
      "What is polymorphism?":"Polymorphism is a feature of object-oriented programming languages that means one name has several variants.",
      "What is DOM?":"The Document Object Model (DOM) is an acronym for Document Object Model, andit is an HTML and XML document programming API. The DOM defines the document’s logical structure and how it is accessed and altered.",
      "Name the operators that cannot be overloaded.":"Scope Resolution operator (::),Pointer-to-member Operator (.*),Member Access or Dot Operator (.),Ternary or conditional operator (?:),Object size Operator (sizeof)",
      "What are some of the differences between C & C++?":"A function is a unit of code that is used for the purpose of reusability of a part of a program. An SQL aggregate function calculates on a set of values and returns a single value. The function should return a value."
}
Amazon={
      "Why do you want to join Amazon?":"The company's growth is increasing rapidly every day, and Amazon has disrupted every industry it has set its foot in every sector in the world.",
      "Why should we hire you?":"As some right out of college, I am on the lookout for opportunities to prove my ability. As a part of this organization, I'll put all my efforts and strengths to make your company reach outstanding achievements, and if you hire me, I will get an opportunity to build my professional experience through your company.",
      "What does success mean to you?":"In my point of view, I define success as fulfilling my role in my team and the company. I trust that my employer has placed me in a position where I can achieve the goals of the company and my team. So I work toward completing my duties as effectively as possible.",
      "What are checked exceptions?":"A checked exception is an exception that occurs at the compile-time; these exceptions are also called compile-time exceptions. The exceptions cannot simply be ignored at the time of compilation, and the programmer should take care of (handle) these exceptions.",
      "What is hashing?":"Hashing is a technique used to convert a range of key values into a range of indexes of an array. For example, you can create an associative data storage where the data index is found by providing its key values using the hash tables.",
      "What is a search operation?":"Search operation means whenever an element is to be searched, start searching from the root node, where the data is less than the key value, search for the element in the left subtree. Or, in simple terms, searching for the element in the right subtree.",
      "What is the purpose of the 'is' operator in Python?":"The 'is' keyword is used to test if two variables refer to the same object or not. The test returns the results true if the two objects are the same object and false if they are not referred to the same object or if the two objects are accurate. Use the == operator to test if two variables are equal.",
      "What is data structure?":"Data structure is a data organization and storage format that enables efficient access and modification of the data. And, a data structure is a collection of data values and the relationships among the data and the functions that can be applied over the data.",
      "What is Collections API?":"Collections API is a set of classes and interfaces that support operations on the collection of objects. The significant advantages of a collections API are that it provides interoperability between unrelated APIs.",
      "What is the Tower of Hanoi?":"The Tower of Hanoi is a puzzle consisting of three towers and more than one ring. Where all rings are of different sizes and stacked upon each other, the large disk is always below the small disk. The main aim is to move the disk tower from one peg to another without breaking its properties.",
}
Apple={
      "Why should we hire you?":"You should hire me for this position because my character,skills,and experience match the type of candidate that Apple is looking for in this position. As requested by the job posting, Iâ€™ve had five years of experience as a product specialist in the technology field and superb customer service and communication skills. Additionally, I have a knack for problem-solving and positivity, which I believe would be extremely useful in this role.",
      "If you accepted a job with Apple, what would you miss most about your current position?":"If I were offered this opportunity to work with Apple, I would be absolutely thrilled, but Iâ€™d also miss certain things about my current position. Mainly, I would miss my amazing co-workers and supervisors at my former place of employment because I grew a great working relationship with them.",
      "Why do you want to join Apple?":"There are two main reasons that I want to work for Apple. First of all, Apple is known to have an extremely supportive work environment that genuinely cares about its employeeâ€™s career growth. I want to be part of a team that will help me pursue my career development for years to come, and Apple seems like the perfect place for that. Also, Apple provides its employees with a work-life balance that I believe would foster my best professional output. All in all, it seems that working for Apple would help me be the best employee I can.",
      "Describe a time that you went above and beyond for a customer.":"When I was working at my very first job as a retail sales associate for a major luxury clothing line, I was handling an average of 100 or more customers every day. A woman had come in and was looking for an outfit to wear to her daughterâ€™s wedding. She was very picky and wanted an associate to help her hold and go through all her options. I ended up spending nearly an hour working with her to find the perfect outfit, but in the end, she left an excellent comment about me with my manager.",
      "How would you handle a co-worker who was distracting you?":"I've worked with a wide array of personalities before, and sometimes even the ones that I like can be distracting in the workplace. I think the best way to handle this circumstance when it arises is by moving forward with direct and professional communication.",
      "What would you do if a customer came in with an iPhone that was not working?":"If a customer came into the Apple store with an iPhone that wasn't working properly, I'd take a few distinct steps to solve the problem.Firstly, I would ask the customer about the history of their device with questions like when they got it, where it was bought and if it had any issues in the past.Next, I'd figure out exactly what the malfunction was to get a better idea of what the cause might be.Then, if it's something in my range of knowledge, I will troubleshoot the issue with them. Otherwise, if it is outside my expertise, I will present the customer with their options for sending the device to the Apple warehouse.",
      "Name three accessibility features that are available on the iPhone.":"Three accessibility features that come to mind as available on todayâ€™s iPhone are the magnifier, text size alteration, and the digital assistant Siri.",
      "What are the different ways of achieving concurrency in iOS?":"iOS has three ways to achieve concurrency:Dispatch queues,Threads,Operation queues",
      "Which JSON framework does iOS support? What are its advantages?":"The SBJson framework is supported by iOS.It has the following key benefits:It is a lightweight data-interchange format, It is easy to read and write for both computers and humans,Server support,Flexible APIs and additional control.",
      "What are the different joins in SQL?":"There are four main types of JOINs in SQL: INNER JOIN, OUTER JOIN, CROSS JOIN, and SELF JOIN. However, remember that OUTER JOINS have two subtypes: LEFT OUTER JOIN and RIGHT OUTER JOIN. Some experts separate also a FULL OUTER JOIN.",
}
Capgemini={
      "Why should one utilise a Database Management System (DBMS)? Explain its advantages?":"The Database Management System (DBMS) is a layer between program and data. It allows users to access and maintain the database. Some of its advantages are:DATA SECURITY, FASTER ACCESS, EASY TO USE",
      "Why is normalisation needed in a database?":"It is essential to normalise the database because it reduces the chance of duplicate data, prevents issues related to data modification and ensures the storage of relevant data only.",
      "What is the difference between UNION and UNION ALL?":"UNION and UNION ALL are SQL operators used to link two or more result sets. The UNION command is used to select the related information from two or more tables. The data type of both the tables must be the same whereas UNION ALL selects the data without removing duplicates or sorting data.",
      "Differentiate between Dataset.clone() and Dataset.copy()?":"Dataset.clone() copies the structure of the dataset. It copies the table schema including the number of rows and columns. However, it does not copy any data. Dataset.copy() copies both the structure and the data from the original data. It copies content along with the table structure.",
      "Differentiate between getch() and getche()?":"The getch() command is done to read a single character from the keyboard and it displays the entered character without using enter key. The getche() function enters the next available keystroke from the console without waiting for the enter key.",
      "What do you know about #pragma directive?":"The #pragma directive is used to provide additional information to the compiler, beyond what is conveyed in the language itself. It is a preprocessor directive for turning on or off specific functionalities.",
      "What is the drawback of scanf() and how can it be avoided (if any)?":"The scanf() will fail with a string of characters. It can not be used to enter a multi-word string into a single variable. One can use the get() function to avoid this.",
      "How is memory managed in Python?":"The memory is managed by Python private heap space. This heap space includes all the data structures and objects.",
      "What are the advantages of NumPy arrays over Python lists?":"The NumPy arrays are preferred over Python lists as they consume less memory, save time, yield faster results and are easier to use.",
      "What is Java String Pool?":"The Java String Pool is a special storage space in Java heap memory. It is used to create and store Java strings. It is also known as String Constant Pool or String Intern Pool.",
}
Cognizant={
      "What are character constants in C++?":"A 'character constant' is formed by enclosing a single character from the representable character set within single quotation marks (' '). Character constants are used to represent characters in the execution character set.",
      "Define the terms OSI, TCP, and IP?":"The full form of TCP/IP is Transmission Control Protocol/ Internet Protocol. The full form of OSI is Open Systems Interconnection. It is a communication protocol that is based on standard protocols and allows the connection of hosts over a network.",
      "Give me a Query to find out the largest compensation in an organization?":"select * from employee where salary=(select Max(salary) from employee);",
      "What are derived data types? Name the user defined data types in C++?":"Derived Data Types are data types that are derived from primitive or built-in data types.They are Function, Array, Pointers, References.",
      "Explain tokens in C++.Also tell about their role and importance?":"In C++, tokens represent the smallest units of a program, including identifiers, keywords, operators, literals, and punctuators. They play a crucial role in syntax analysis and compilation, forming the building blocks of C++ code, and enabling the compiler to understand and process the program structure accurately.",
      "Can a database table exist without a primary key?":"Yes, a database table can exist without a primary key, but it may lead to issues like inefficient data retrieval and potential data duplication. A primary key uniquely identifies each record in a table, facilitating faster queries and ensuring data integrity by preventing duplicate entries.",
      "What is the reason behind using Inner Join and Outer Join?":"The biggest difference between an INNER JOIN and an OUTER JOIN is that the inner join will keep only the information from both tables that's related to each other (in the resulting table). An Outer Join, on the other hand, will also keep information that is not related to the other table in the resulting table.",
      "What is the top-n analysis in DBMS?":"TOP-N analysis is used to limit the number of rows returned from an ordered set of data items. This are very useful when you would like to return the N lowest or highest rows.",
      "What is object oriented model?":"The Object-Oriented Model in DBMS or OODM is the data model where data is stored in the form of objects. This model is used to represent real-world entities. The data and data relationship is stored together in a single entity known as an object in the Object Oriented Model. The Object-Oriented Database Management System is built on top of Object Oriented Model.",
      "Define RDBMS.":"The software used to store, manage, query, and retrieve data stored in a relational database is called a relational database management system (RDBMS). The RDBMS provides an interface between users and applications and the database, as well as administrative functions for managing data storage, access, and performance.",
}
Deloitte={
      "What is backpropagation?":"Backpropagation is a common way for an artificial neural network to figure out the gradient of the loss function for the weights. It is often used as part of algorithms that change the consequences to improve the performance of a network.",
      "What is the difference between a crossover and a straight-through?":"Straight-through is between a modem and a computer, switch, or router .Connecting a computer to a switch,router to a hub.Cross over is Between two networking devices connection between hubs &switches.",
      "What is SMTP?":"SMTP (Simple Mail Transfer Protocol) deals with internet mail and important mail delivery services on the IP/TCP protocol stack.",
      "What made you want to find a new job?":"I am looking for a switch to explore opportunities for professional growth.I would to learn and upgrade my skill sets through new challenges.",
      "Why should we hire you Deloitte?":" I am a hardworking person who likes to take on challenges. I am able to meet deadlines since I have good time management skills.",
      "What is a volatile keyword?":"A volatile keyword is a way to make the class thread-safe. This means that multiple threads can use a class instance simultaneously without any trouble.",
      "What are the differences between stored procedure and triggers in SQL?":"Stored procedures are small pieces of PL/SQL code that perform a specific task,Trigger, on the other hand, is a stored process that executes automatically when certain events occur (eg update, insert, delete in a database).",
      "What do you understand about tunneling protocol in Computer Networks?":"A tunneling protocol is a communications protocol that allows data to be moved from one network to another. Through a technique known as encapsulation, private network communications can be sent via a public network.",
      "Discuss the physical layer of the OSI Model in context of Computer Networks?":"Physical layer is the lowest layer in OSI model.Bits of information are stored in the physical layer. It is in charge of sending individual bits from one node to another. When this layer receives data, it converts the signal received into 0s and 1s and sends them to the Data Link layer.",
      "How can you contribute to the growth of our company?":"My dream job would be a leadership position where the other team members are active participants and communication happens daily.",
}
Google={
      "What is your knowledge of Google's history":"Headquartered in Mountain View, California, Google LLC, formerly Google Inc. (1998-2017),Google just focused on its search function, but now it offers a multitude of products such as email, document-creation software, and more.",
      "In your opinion, should people have to use their legal names when setting up a Gmail account?":"Although it is required by Google, you don't need to use your real name (or the Google username of your choice) to complete this profile.",
      "What do you think of Google charging for their productivity apps? Do you agree or disagree?":"I disagree with Google charging for their productivity apps. By charging for these apps, it will be difficult for them to get a large user base, as not everyone is willing to pay for software.",
      "What does multithreaded programming mean?":"A multithreaded program is an executable program with multiple execution threads, each running on its own processor.",
      "If you were told to create an initiative to increase Gmail's user base, what would you do?":"Prioritizing users: Since normal users constitute most part of the Gmail user base, it becomes important to focus on this user segment to improve user engagement and therefore improve the stickiness, and revenue of google from Gmail.",
      "How do cookies move along through the HTTP protocol?":"A cookie is transmitted as part of an HTTP protocol via a header field. Cookie lifecycle: The first time a browser connects with a particular server, there are no cookies. The server creates a unique identifier, and returns a Set-Cookie: header in the response that contains the identifier.",
      "What steps could YouTube take to improve its business model?":"YouTube is currently a free platform for users and makes money primarily through advertisements. YouTube could possibly create paid accounts for users who wish to avoid ads. Another option would be to offer users pay-per-view videos and exclusive content only available with a subscription.",
      "Could you explain why the Google homepage is mostly blank?":"In the wake of annoying pop-ups and advertisements, the Google founders have made it simple for the users, which ultimately led to a better interface.",
      "What is Google's largest concern right now?":"For a while now, Microsoft has been Google's biggest threat.",
      "Given an autosuggest issue in a developing country, what steps would you take to correct it?":"Identify keywords that are being searched frequently in your country, and then test those out for feasibility as suggested search terms by watching live autosuggest results, testing out potential abbreviations, etc. 2. Try to find similar countries or regions where you can test it first before launching it on a larger scale.",
}
Microsoft={
      "Define objects and classes in C++?":"A class's instance is an object. An object can be referred to as a variable of a class because it is a user-defined data type.",
      "In C++, how do you allocate and release memory?":"In C++, the new operator is used to allocate memory, whereas the delete operator is used to deallocate memory.",
      "What are Microsoft security patches?":"Microsoft security patches are intended to solve certain security loopholes and problems, while at the same time upgrading any existing security features.",
      "What is the difference between standard modules and class modules?":"Standard modules contain variables, procedures and functions that are accessible anywhere within the project. A class module contains properties and events, and is made accessible only by objects that were created as an instance of that class.",
      "Why is it that you cannot overload the scope resolution operator (::)?":"main reason why the (::) cannot be overloaded is that only operators that take in values as parameters can be overloaded. The scope resolution operator does not take a value as parameter.",
      "What is plug and play?":"Plug and Play is a technology wherein hardware components that are installed on PCs using Microsoft operating system are immediately recognized and made usable.",
      "Why is code optimization important?":"Optimized code tends to run faster and make more efficient use of the systemâ€™s resources. Optimized codes are also less susceptible to errors and take lesser space in memory and in file size.",
      "Why are there different Microsoft Certifications?":"Microsoft Certification covers a wide list of technology and is recognize worldwide.",
      "Which Microsoft Certification is considered the most popular?":"It is Microsoft Certified Systems Engineer (MCSE). This certification deals with skills related to applying solutions to business productivity by utilizing Microsoft Server operating system.",
      "Why do you want to work for Microsoft?":"Association with the company as Microsoft will shape my career in a great way. The history and achievement of Microsoft over the years, has inspired me to be a part of their upcoming achievements.",
}
Devops={
    "What is DevOps?":"DevOps is a set of practices that combines software development (Dev) and IT operations (Ops). It aims to shorten the software development lifecycle and provide continuous delivery of high-quality software.",
    "What are the key components of DevOps?":"The key components of DevOps include collaboration, automation, continuous integration, continuous delivery, and monitoring",
    "What is the role of version control in DevOps?":"Version control systems (e.g., Git, SVN) are essential in DevOps for managing changes to source code, tracking revisions, and enabling collaboration among team members",
    "What is continuous integration (CI) in DevOps?":"Continuous integration is the practice of frequently integrating code changes into a shared repository. Each integration is verified by an automated build and automated tests, allowing teams to detect and fix issues early.",
    "What is continuous delivery (CD) in DevOps?":"Continuous delivery is the practice of ensuring that code changes can be deployed to production quickly and safely. It involves automating the deployment process and having a reliable release pipeline",
    "What is infrastructure as code (IaC) in DevOps?":"Infrastructure as code is the practice of managing and provisioning infrastructure through code and automation tools. It allows for the consistent and repeatable creation of infrastructure, reducing manual work and errors",
    "What is the role of containers in DevOps?":"Containers, such as Docker, provide a lightweight and portable way to package and run applications. They help in achieving consistency across different environments and enable more efficient use of resources.",
    "What is continuous monitoring in DevOps?":"Continuous monitoring involves monitoring the performance and health of applications and infrastructure in real-time. It helps in detecting and responding to issues quickly, ensuring the reliability of systems.",
    "What is the difference between continuous deployment and continuous delivery?":"Continuous deployment is the practice of automatically deploying every code change to production, while continuous delivery is the practice of ensuring that code changes can be deployed to production at any time but may not necessarily be deployed automatically.",
    "What are some key benefits of implementing DevOps practices?":"Some key benefits of implementing DevOps practices include faster delivery of features, improved collaboration between teams, increased efficiency and productivity, and better reliability and security of software systems."
}
Cyber_Security={
    "What is cybersecurity?":"Cybersecurity is the practice of protecting computer systems, networks, and data from digital attacks, theft, and damage.",
    "What are the main goals of cybersecurity?":"The main goals of cybersecurity are to ensure the confidentiality, integrity, and availability of information and systems.",
    "What is the CIA triad in cybersecurity?":"The CIA triad stands for Confidentiality, Integrity, and Availability, which are the three core principles of cybersecurity.",
    "What is a firewall?":"A firewall is a network security device that monitors and controls incoming and outgoing network traffic based on predetermined security rules.",
    "What is encryption?":"Encryption is the process of converting data into a secure format that can only be read or accessed with the correct decryption key.",
    "What is a vulnerability assessment?":"A vulnerability assessment is the process of identifying and evaluating vulnerabilities in a system or network to determine potential security risks.",
    "What is a phishing attack?":"A phishing attack is a type of cyber attack in which attackers use fraudulent emails or messages to trick individuals into providing sensitive information such as passwords or credit card numbers.",
    "What is a DDoS attack?":"A DDoS (Distributed Denial of Service) attack is a cyber attack in which multiple compromised systems are used to flood a target system or network with an overwhelming amount of traffic, causing it to become unavailable.",
    "What is endpoint security?":"Endpoint security refers to the protection of endpoint devices such as laptops, desktops, and mobile devices from cyber threats.",
    "What is the difference between penetration testing and vulnerability scanning?":"Penetration testing involves simulating real-world cyber attacks to identify and exploit vulnerabilities in a system, while vulnerability scanning involves scanning a system to identify and report on potential vulnerabilities without actually exploiting them."
}
ML={
    "What is machine learning?":"Machine learning is a subset of artificial intelligence that involves the development of algorithms and statistical models that enable computers to improve their performance on a specific task without being explicitly programmed.",
    "What are the main types of machine learning?":"The main types of machine learning are supervised learning, unsupervised learning, and reinforcement learning.",
    "Can you explain the difference between supervised and unsupervised learning?":"Supervised learning involves training a model on a labeled dataset, where each training example is paired with the correct label. Unsupervised learning involves training a model on an unlabeled dataset and allowing the model to find patterns in the data on its own.",
    "What is overfitting in machine learning?":"Overfitting occurs when a machine learning model performs well on the training data but fails to generalize to new, unseen data. This typically happens when the model is too complex or when it is trained on too little data.",
    "How do you prevent overfitting in a machine learning model?":"To prevent overfitting, you can use techniques such as cross-validation, regularization, and early stopping. These techniques help to ensure that the model generalizes well to new data.",
    "What is the bias-variance tradeoff in machine learning?":"The bias-variance tradeoff is a fundamental concept in machine learning that refers to the balance between bias and variance in a model. A high-bias model is likely to underfit the data, while a high-variance model is likely to overfit the data.",
    "What is the difference between batch gradient descent and stochastic gradient descent?":"Batch gradient descent calculates the gradient of the cost function using the entire training dataset, while stochastic gradient descent calculates the gradient using only one training example at a time. Stochastic gradient descent is often faster but may be more prone to noisy data.",
    "What is a confusion matrix?":"A confusion matrix is a table that is used to evaluate the performance of a classification model. It shows the number of true positives, true negatives, false positives, and false negatives.",
    "What is precision and recall?":"Precision is the ratio of true positives to the sum of true positives and false positives, and it measures the accuracy of positive predictions. Recall is the ratio of true positives to the sum of true positives and false negatives, and it measures the ability of the model to correctly identify positive instances.",
    "What is cross-validation?":"Cross-validation is a technique used to evaluate the performance of a machine learning model. It involves splitting the dataset into multiple subsets, training the model on some subsets, and testing it on the remaining subset. This process is repeated multiple times, and the results are averaged to obtain a more reliable estimate of the model's performance."
}
AWS={
    "What are the 3 types of cloud services AWS has?":"three Types of Cloud Computing,Infrastructure as a Service(Iaas),Platform as a Service(PaaS),Software as a Service(SaaS)",
    "What is the relation between the Availability Zone and Region?":"AWS regions are separate geographical areas, like the US-West(North California) and AsiaSouth (Mumbai) and availability zones are the areas that are present inside the regions",
    "What is auto-scaling?":"Auto Scaling monitors your applications and automatically adjusts capacity to maintain steady, predictable performance at the lowest possible cost",
    "what is cloudwatch?":"CloudWatch enables you to monitor your complete stack (applications, infrastructure, network, and services) and use alarms, logs, and events data to take automated actions and reduce mean time to resolution (MTTR).",
    "What is an Elastic Transcoder?":"Amazon Elastic Transcoder is media transcoding in the cloud.",
    "What is AWS?":"Amazon Web Services (AWS) is a Comprehensive Cloud platform that offers more than 165 services such as database storage, content delivery, security infrastructure,from data centers worldwide",
    "What are the main components of AWS?":"Simple Email service,Route 53,Simple Storage Device S3,Elastic compute cloud( EC2),Elastic Block Store,Cloud watch",
    "What is the importance of buffer in AWS?":"A buffer helps to integrate and synchronize various components in AWS and helps to maintain equilibrium by linking multiple apparatus to deliver quick services at a uniform rate.",
    "What are key-pairs?":"Key Pairs are used to connect to the virtual machines. The secure login credentials used to connect to virtual machines are known as Key pairs.",
    "What is an AMI?":"Amazon Machine Image contains various software configurations, block device mapping for allocating volumes to the virtual machine and launch permissions"
}
AI={
    "What is Artificial Intelligence?":"Artificial Intelligence (AI) is a stream of computer science that enhances the intelligent machines that work and react like humans. The ability of a machine to simulate intelligent human behavior",
    "List out the various applications of AI?":"Chatbots,Self-driving cars,Image tagging,AI in healthcare,AI in eCommerce,Human Resource Management,Intelligent Cybersecurity,AI to enhance workplace communication, Facial expression recognition",
    "How many Types of Artificial Intelligence are there? What are they?":"There are four types and those are Reactive Machines AI,Limited Memory AI,Theory of Mind AI,Self Aware AI.",
    "What are the stages of learning AI?":"The learning stages are Artificial General Intelligence (AGI),Artificial Normal Intelligence (ANI),Artificial Super Intelligence (ASI)",
    "What is an intelligent agent in Artificial Intelligence?":"An Intelligent Agent (IA) refers to an autonomous entity that acts as a directing its activity to achieve goals as an agent upon an environment using observation by actuators and sensors as an intelligent.",
    "What is the difference between Strong AI and Weak AI?":"With strong AI, machines can think and perform tasks as their own, as humans do. With Weak AI, the machines cannot perform tasks independently; instead, it depends heavily on human interference.", 
    "What are the commonly used types of neural networks in AI?":"recurrent neural networks,Feedforward neural networks,Convolution neural networks",
    "What is an Artificial Neural Network?":"An Artificial Neural Network (ANN) is a computing system designed to simulate the human brain's analysis and processes of information.", 
    "What is the Turing test?":"The Turing Test is a process of inquiry in Artificial Intelligence (AI) to determine whether a computer or not, which is capable of thinking like a human being.", 
    "What is FOPL in Artificial Intelligence?":"FOPL means First Order Predicate Logic"
}
Front_End={
    "What npm stands for ?":"Npm stands for Node Package Manager.",
    "What is scope in JavaScript? ":"In JavaScript every function has its own scope. It is basically a collection of rules for how variables are accessed and variables itself.",
    "What is User Centered Design?":"User-centered designs are those designs the designer solely focuses on which are according to the needs of users and them in every phase of designing.", 
    "What is Coercion in JavaScript?":"The conversion of two different build-in Types of JavaScript is called Coercion. It comes in two forms, Explicit and implicit.", 
    "What is IIFEs?":"IIFEs stands for Immediately-Invoked Function Expression. This executes immediately after you create it.",
    "State the elements of the CSS Box Model?":"CSS Box Model consist of 4 elements Content,Padding,Border,Margin",
    "How are JavaScript and jQuery different?":"JQuery is a library built with the JavaScript language, and JavaScript is the language itself.", 
    "What is Content Security Policy?":"Content security Policy also known as CSP, is a header in HTML which lets the soite operators gain the whole control over the resources which are loading on the site.", 
    "What is Cross-Site Scripting (XSS)?":"XSS, Cross-Site Scripting is an attack which takes place when any attacker uses a web application to send any malicious code, in the form of browser side script, to another user.", 
    "State some basic design element?":"Some of the basic elements of design are Line,Size,Texture,Color"
}